### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [nmWolfe/beer-garden#2]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages): DONE
2. A public GitHub repository for your codebase: DONE
3. Using Punk API: DONE
4. Tests where possible RTL: STARTED

### Plan

- Start:
  - Matching component tree & passing props? DONE
- Stage 1:
  - Search functionality? DONE
- Stage 2:
  - Filters x 3? DONE
- Stage 3:
  - Styled? DONE

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Union-Course-Resources/blob/main/student-resources/03-react/punk-api-marking-scheme.md)

| Category          | Score    |
| ----------------- | -------- |
| Functionality     | 45 / 55  |
| Testing           | 0 / 10   |
| Project Structure | 10 / 10  |
| React Use         | 20 / 20  |
| Design            | 15 / 15  |
| Total Score       | 90 / 110 |

## Positive

- Again I have got to give you kudos for your tenacity you have extended the brief by adding different sorts & filters. 

- You have multiple functions and bits of data being passed across your application to the components that need them using props!

- You are utilizing the power of query params to do your filtering for you!

- You have started testing I think you will enjoy having a look at this [Testing repo](https://github.com/nology-tech/thrones-reindeer) it has more complex tests which would be good for your reference. 

  - There are some examples of how you can separate your fetch into a service & test it & the components that use it.

- I feel confident with your understanding of props, useState, useEffect and funcs as props.
  - I have a little pointer about useEffect below. 

- Awesome, good going! it is a big project and I can't wait to see what you build next.

## Constructive

- On my monitor, I am getting lots of scroll boxes, would be worth fixing that. 

- We are not writing python here :P, use camelCasing not snake_casing for props & variables.

  - `beer_list` should be `beerList`

- I can see you have used the API to apply a single filter, This is great and I think that the way you have set up your `getBeer()` function is holding you back from applying multiple filters. You also have some repetition in it so you can also refactor it see below.
  - This will not mean you can add multiple query params but should give you a good hint as to how you could.

```tsx
// App.tsx

const getBeers = async () => {
  try {
    // REPETITION IN EACH BLOCK & LOCKED TO USE SET URL FOR FETCH
    if (filter.searchText.length >= 1) {
      const url = `https://api.punkapi.com/v2/beers?page=${page}&per_page=${beerDisplayAmount}&beer_name=${filter.searchText}`;
      const response = await fetch(url);
      const data: Beer[] = await response.json();
      setBeers(data);
    } else if (filter.radioSelect !== "all") {
      const url = `https://api.punkapi.com/v2/beers?page=${page}&per_page=${beerDisplayAmount}&${filter.radioSelect}`;
      const response = await fetch(url);
      const data: Beer[] = await response.json();
      setBeers(data);
    } else {
      const url = `https://api.punkapi.com/v2/beers?page=${page}&per_page=${beerDisplayAmount}`;
      const response = await fetch(url);
      const data: Beer[] = await response.json();
      setBeers(data);
    }
  } catch (error) {
    console.log("There was an error" + error);
  }
};

// COULD BE

const getBeers = async () => {
  try {
    // URL IS THE THING THAT CHANGES
    // HAVE A BASE URL
    // IF YOUR CONDITION IS MET ADD ON THE QUERY PARAM
    let url = `https://api.punkapi.com/v2/beers?page=${page}&per_page=${beerDisplayAmount}`;
    if (filter.searchText.length >= 1) {
      url += `&beer_name=${filter.searchText}`;
    } else if (filter.radioSelect !== "all") {
      url += `&${filter.radioSelect}`;
    }
    const response = await fetch(url);
    const data: Beer[] = await response.json();
    setBeers(data);
  } catch (error) {
    console.log("There was an error" + error);
  }
};
```

- Remove `// eslint-disable-next-line react-hooks/exhaustive-deps` from your useEffect. You can refactor your function to remove the warning see notes below.
  - It is confusing at first so reach out if you want an explanation.

```tsx
// App.tsx

const getBeers = async () => {
 // CODE IN HERE RELIES ON THESE STATE VARIABLES
 // - beerDisplayAmount, page, filter
 // WHEN THEY CHANGE THE FUNCTION NEEDS TO BE RECREATED TO WORK WITH THEM
 // - YOU CAN THINK OF THESE AS HARD CODED VALUES WHEN A COMPONENT IS RENDERED

  try {
    if (filter.searchText.length >= 1) {
      const url = `https://api.punkapi.com/v2/beers?page=${page}&per_page=${beerDisplayAmount}&beer_name=${filter.searchText}`;
    }
    // REST OF CODE...
  }
}

useEffect(() => {
  getBeers();
  // THIS IS WHY YOU NEED THIS LINE
  // eslint-disable-next-line react-hooks/exhaustive-deps
}, [beerDisplayAmount, page, filter]);

// SHOULD BE

const getBeers = async (displayAmount: number, pageNumber:number, filterObject: FilterType) => {
 // CODE IN HERE NOW RELIES ON PARAMETERS RATHER THEN STATE
 // THE FUNCTION DOES NOT NEED TO BE RECREATED AS THE VALUES ARE PASSED IN AS PARAMETERS
 // - NOT HARDCODED

  try {
    if (filter.searchText.length >= 1) {
      const url = `https://api.punkapi.com/v2/beers?page=${pageNumber}&per_page=${displayAmount}&beer_name=${filterObject.searchText}`;
    }
    // REST OF CODE...
    // - USING PARAMETERS ^^ NOT STATE
  }
}

useEffect(() => {
  // GIVE THE FUNCTION THE PARAMETERS IT NEEDS
  // - PASS IN THE STATE VALUES
  getBeers(beerDisplayAmount, page, filter);
}, [beerDisplayAmount, page, filter]);
```

---

**Comment by nmWolfe** [comment]
Thanks Charlie! 
I realised after doing the getBeers call, that I should have just kept the base URL, and added the extensions with variables. 
Great feedback, once again. Thank you!
